name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --immutable --immutable-cache
      - run: yarn workspace craco-babel-loader build
      - run: yarn workspace cra-app test
